// Code generated by metactl. DO NOT EDIT.
// source: protos/pbdef/*.proto

package meta

func init()  {
	registerMeta(C2S_FETCH_CONFIG)
	registerMeta(C2S_PLAYER_LOGIN)
	registerMeta(C2S_PLAYER_PLAYING)
	registerMeta(C2S_PLAYER_LOGOUT)
}