// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: common.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgID int32

const (
	MsgID_UNKNOW_MessageID   MsgID = 0
	MsgID_C2S_FETCH_CONFIG   MsgID = 100
	MsgID_C2S_PLAYER_LOGIN   MsgID = 101
	MsgID_C2S_PLAYER_PLAYING MsgID = 102
	MsgID_C2S_PLAYER_LOGOUT  MsgID = 103
)

var MsgID_name = map[int32]string{
	0:   "UNKNOW_MessageID",
	100: "C2S_FETCH_CONFIG",
	101: "C2S_PLAYER_LOGIN",
	102: "C2S_PLAYER_PLAYING",
	103: "C2S_PLAYER_LOGOUT",
}

var MsgID_value = map[string]int32{
	"UNKNOW_MessageID":   0,
	"C2S_FETCH_CONFIG":   100,
	"C2S_PLAYER_LOGIN":   101,
	"C2S_PLAYER_PLAYING": 102,
	"C2S_PLAYER_LOGOUT":  103,
}

func (x MsgID) String() string {
	return proto.EnumName(MsgID_name, int32(x))
}

func (MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

type MsgType int32

const (
	MsgType_Unknown MsgType = 0
	MsgType_Req     MsgType = 1
	MsgType_Reply   MsgType = 2
	MsgType_Push    MsgType = 3
	MsgType_Err     MsgType = 4
)

var MsgType_name = map[int32]string{
	0: "Unknown",
	1: "Req",
	2: "Reply",
	3: "Push",
	4: "Err",
}

var MsgType_value = map[string]int32{
	"Unknown": 0,
	"Req":     1,
	"Reply":   2,
	"Push":    3,
	"Err":     4,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

type PkgMsg struct {
	Type                 MsgType  `protobuf:"varint,1,opt,name=Type,proto3,enum=pb.MsgType" json:"Type,omitempty"`
	Msgid                MsgID    `protobuf:"varint,2,opt,name=Msgid,proto3,enum=pb.MsgID" json:"Msgid,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkgMsg) Reset()         { *m = PkgMsg{} }
func (m *PkgMsg) String() string { return proto.CompactTextString(m) }
func (*PkgMsg) ProtoMessage()    {}
func (*PkgMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}
func (m *PkgMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PkgMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PkgMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PkgMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgMsg.Merge(m, src)
}
func (m *PkgMsg) XXX_Size() int {
	return m.Size()
}
func (m *PkgMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PkgMsg proto.InternalMessageInfo

func (m *PkgMsg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_Unknown
}

func (m *PkgMsg) GetMsgid() MsgID {
	if m != nil {
		return m.Msgid
	}
	return MsgID_UNKNOW_MessageID
}

func (m *PkgMsg) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ErrMsg struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrMsg) Reset()         { *m = ErrMsg{} }
func (m *ErrMsg) String() string { return proto.CompactTextString(m) }
func (*ErrMsg) ProtoMessage()    {}
func (*ErrMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}
func (m *ErrMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ErrMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ErrMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ErrMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrMsg.Merge(m, src)
}
func (m *ErrMsg) XXX_Size() int {
	return m.Size()
}
func (m *ErrMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ErrMsg proto.InternalMessageInfo

func (m *ErrMsg) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ErrMsg) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.MsgID", MsgID_name, MsgID_value)
	proto.RegisterEnum("pb.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*PkgMsg)(nil), "pb.PkgMsg")
	proto.RegisterType((*ErrMsg)(nil), "pb.ErrMsg")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x19, 0x5a, 0xa8, 0x5c, 0x88, 0x19, 0x6f, 0xd4, 0x74, 0x55, 0x08, 0x2b, 0xc2, 0xa2,
	0x0b, 0x5c, 0xbb, 0xd0, 0x52, 0xb0, 0x91, 0xfe, 0x64, 0x84, 0x18, 0x57, 0x0d, 0xd8, 0x3a, 0x1a,
	0xa0, 0x53, 0x3b, 0x1a, 0xe5, 0x4d, 0x7c, 0x24, 0x97, 0x3e, 0x82, 0xa9, 0x2f, 0x62, 0x5a, 0x20,
	0xd1, 0xd5, 0x9c, 0xf9, 0xce, 0xc9, 0x3d, 0xb9, 0x17, 0x5a, 0xf7, 0x62, 0xbd, 0x16, 0x89, 0x99,
	0x66, 0xe2, 0x45, 0x60, 0x35, 0x5d, 0x74, 0x23, 0xa8, 0x07, 0x4b, 0xee, 0x4a, 0x8e, 0x6d, 0x50,
	0xa7, 0x9b, 0x34, 0xd6, 0x49, 0x87, 0xf4, 0x0e, 0x07, 0x4d, 0x33, 0x5d, 0x98, 0xae, 0xe4, 0x05,
	0x62, 0xa5, 0x81, 0x6d, 0xa8, 0xb9, 0x92, 0x3f, 0x45, 0x7a, 0xb5, 0x4c, 0x34, 0x76, 0x09, 0x67,
	0xc8, 0xb6, 0x1c, 0x75, 0xd0, 0x82, 0xf9, 0x66, 0x25, 0xe6, 0x91, 0xae, 0x74, 0x48, 0xaf, 0xc5,
	0xf6, 0xdf, 0xae, 0x09, 0x75, 0x3b, 0xcb, 0x8a, 0x16, 0x04, 0xd5, 0x12, 0xd1, 0xb6, 0xa5, 0xc6,
	0x4a, 0x8d, 0x14, 0x14, 0x57, 0xf2, 0x72, 0x6c, 0x83, 0x15, 0xb2, 0xff, 0x5e, 0x56, 0x39, 0x43,
	0x3c, 0x06, 0x3a, 0xf3, 0xae, 0x3d, 0xff, 0x36, 0x74, 0x63, 0x29, 0xe7, 0x3c, 0x76, 0x86, 0xb4,
	0x52, 0x50, 0x6b, 0x70, 0x13, 0x8e, 0xec, 0xa9, 0x75, 0x15, 0x5a, 0xbe, 0x37, 0x72, 0xc6, 0x34,
	0xda, 0xd3, 0x60, 0x72, 0x71, 0x67, 0xb3, 0x70, 0xe2, 0x8f, 0x1d, 0x8f, 0xc6, 0x78, 0x0a, 0xf8,
	0x87, 0x16, 0x8f, 0xe3, 0x8d, 0xe9, 0x03, 0x9e, 0xc0, 0xd1, 0xff, 0xb4, 0x3f, 0x9b, 0x52, 0xde,
	0x3f, 0x07, 0x6d, 0xb7, 0x35, 0x36, 0x41, 0x9b, 0x25, 0xcb, 0x44, 0xbc, 0x25, 0xb4, 0x82, 0x1a,
	0x28, 0x2c, 0x7e, 0xa6, 0x04, 0x1b, 0x50, 0x63, 0x71, 0xba, 0xda, 0xd0, 0x2a, 0x1e, 0x80, 0x1a,
	0xbc, 0xca, 0x47, 0xaa, 0x14, 0xae, 0x9d, 0x65, 0x54, 0xbd, 0xa4, 0x9f, 0xb9, 0x41, 0xbe, 0x72,
	0x83, 0x7c, 0xe7, 0x06, 0xf9, 0xf8, 0x31, 0x2a, 0x8b, 0x7a, 0x79, 0xeb, 0xb3, 0xdf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x53, 0xd0, 0xd2, 0x6d, 0x7b, 0x01, 0x00, 0x00,
}

func (m *PkgMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PkgMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PkgMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Msgid != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.Msgid))
		i--
		dAtA[i] = 0x10
	}
	if m.Type != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ErrMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ErrMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ErrMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Msg) > 0 {
		i -= len(m.Msg)
		copy(dAtA[i:], m.Msg)
		i = encodeVarintCommon(dAtA, i, uint64(len(m.Msg)))
		i--
		dAtA[i] = 0x12
	}
	if m.Code != 0 {
		i = encodeVarintCommon(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCommon(dAtA []byte, offset int, v uint64) int {
	offset -= sovCommon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PkgMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovCommon(uint64(m.Type))
	}
	if m.Msgid != 0 {
		n += 1 + sovCommon(uint64(m.Msgid))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ErrMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovCommon(uint64(m.Code))
	}
	l = len(m.Msg)
	if l > 0 {
		n += 1 + l + sovCommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCommon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCommon(x uint64) (n int) {
	return sovCommon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PkgMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PkgMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PkgMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= MsgType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msgid", wireType)
			}
			m.Msgid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Msgid |= MsgID(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ErrMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ErrMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ErrMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Msg", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Msg = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCommon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCommon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCommon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCommon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCommon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCommon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCommon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCommon = fmt.Errorf("proto: unexpected end of group")
)
